name: Daily Political News Digest

on:
  schedule:
    # Run Belgium politics digest at 5:00 AM UTC every day
    - cron: '0 5 * * *'
    # Run world politics digest at 5:00 AM UTC every day
    - cron: '0 5 * * *'

  # Allow manual triggering from GitHub UI
  workflow_dispatch:
    inputs:
      digest_type:
        description: 'Type of digest to run'
        required: true
        type: choice
        options:
          - belgium_politics
          - world_politics
          - all

jobs:
  belgium-politics-digest:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'schedule' && github.event.schedule == '0 7 * * *') ||
      (github.event_name == 'workflow_dispatch' && (github.event.inputs.digest_type == 'belgium_politics' || github.event.inputs.digest_type == 'all'))
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Run Belgium politics digest
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          BE_POLITICS_DISCORD_WEBHOOK_URL: ${{ secrets.BE_POLITICS_DISCORD_WEBHOOK_URL }}
        run: |
          python main.py belgium_politics

  world-politics-digest:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'schedule' && github.event.schedule == '30 7 * * *') ||
      (github.event_name == 'workflow_dispatch' && (github.event.inputs.digest_type == 'world_politics' || github.event.inputs.digest_type == 'all'))
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Run world politics digest
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          WORLD_NEWS_DISCORD_WEBHOOK_URL: ${{ secrets.WORLD_NEWS_DISCORD_WEBHOOK_URL }}
        run: |
          python main.py world_politics
